### ISSUE TITLE
Technical Planning Meeting to breakdown task

### ISSUE THREAD

**Issue by uon-rcking** [99904047/S2C5-Stop-SO13-for-sales-invoicing-being-emailed#1]

**Comment by 99904047** [comment]
At the technical planning meeting the following sub tasks where agreed, roy will need to allocate points, milestones and task owners to them.

1 - Scope the SO13 variants requiring the functionality to be removed - TO (task owner) KO
2 - implement the removal within test - TO MMD
3 - UAT -TO KO
4 - implement changes in live - TO JB
5 - documentation - TO MMD
6 - Signoff by TO - TO KO
