### ISSUE TITLE
Acquire SO13 List

### ISSUE THREAD

**Issue by uon-rcking** [99904047/S2C5-Stop-SO13-for-sales-invoicing-being-emailed#2]

**Comment by 99904047** [comment]
I have emailed Janet this morning asking for a list of the SO10 report variants needing the email parameter removed

**Comment by uon-jbaine** [comment]
Variant 1  Disability Support Allowance Invoice
Variant 2   Disability Support Allowance credit Note
Variant 3  Occam Automatic Rent Invoice
Variant 4 Occam Automatic Rent Credit Note
Variant 5  Ad Hoc Invoice
Variant 6  Ad Hoc Credit Note
Variant 7  Field Trip Invoice
Variant 8  Field Trip Credit Note
Variant 9 Emergency Loans Invoice
Variant 10 Emergency Loans Credit Note
Variant 11 Studio Levies Invoice
Variant 12 Studio Levies Credit Note
Variant 13 Short Courses Invoice
Variant 14 Short Courses Credit Note
Variant 15  Conference Invoices
Variant 16  Conference Credit Notes
Variant 17 Additional Modules Invoice
Variant 18 Additional Modules Credit Note
Variant 19 TuitionFee Invoices
Variant 20 Tuition Fee Credit Notes
Variant 23  Manual Rent Invoice
Variant 24 Manual Rent Credit Note
